# Generated by Django 5.1.5 on 2025-02-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoo',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], default='P', max_length=10),
        ),
    ]
